[package]
name = "roomor"
version = "0.3.8"
edition = "2021"
authors = ["Roman Chumak <p4ymak@yandex.ru>"]
description = "Minimalistic offline chat over local network."
license = "MIT"
repository = "https://github.com/p4ymak/roomor"
readme = "README.md"
categories = ["network-programming"]
keywords = ["chat", "lan", "offline"]
resolver = "2"

[dependencies]
eframe = "0.29"
rfd = "0.15"
human_bytes = "0.4.3"
opener = "0.7.2"
egui-phosphor = "0.7.3"
flume = "0.11.0"

whoami = "1.5.2"
directories = "5.0.1"
chrono = "0.4.38"
timediff = "0.2.3"

enumn = "0.1.14"
crc = "3.2.1"
range_rover = "0.1.2"

rodio = { version = "0.19.0", default-features = false }
notify-rust = "4"

image = "0.25.2"

log = { version = "0.4", features = ["std"] }
env_logger = "0.11.5"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
strip = "debuginfo"

[package.metadata.bundle]
name = "Roomor"
identifier = "com.p4ymak.roomor"
icon = ["icon/128x128.png"]
version = "0.3.8"
short_description = "Minimalistic offline chat over local network."
long_description = "Minimalistic offline chat over local network."
deb_depends = ["libgl1-mesa-glx", "libsdl2-2.0-0 (>= 2.0.5)"]
osx_frameworks = ["SDL2"]
