[package]
name = "udp_chat"
version = "0.1.0"
edition = "2021"
authors = ["Roman Chumak <p4ymak@gmail.com>"]
resolver = "2"
description = "Chat over local network."

[dependencies]
local_ipaddress = "0.1.3"
eframe = "0.15.0"
chrono = "0.4.19"
directories = "4.0.1"
enumn = "0.1.3"
crc = "2.1.0"
log = "0.4.14"
rusqlite = {version = "0.26.3", features = ["bundled"]}

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
