[package]
name = "udp_chat"
version = "0.2.0"
edition = "2021"
authors = ["Roman Chumak <p4ymak@yandex.ru>"]
resolver = "2"
description = "Chat over local network."

[dependencies]
local_ipaddress = "0.1.3"
eframe = "0.26.0"
chrono = "0.4.34"
directories = "5.0.1"
enumn = "0.1.13"
crc = "3.0.1"
log = "0.4.20"
env_logger = "0.11.1"
rusqlite = {version = "0.30.0", features = ["bundled"]}

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
