[package]
name = "roomor"
version = "0.2.1"
edition = "2021"
authors = ["Roman Chumak <p4ymak@yandex.ru>"]
description = "Minimalistic offline chat over local network."
license = "MIT"
repository = "https://github.com/p4ymak/roomor"
readme = "README.md"
categories = ["network-programming"]
keywords = ["chat", "lan", "offline"]
resolver = "2"

[dependencies]
eframe = "0.26.2"
flume = "0.11.0"

ipnet = "2.9.0"
chrono = "0.4.34"
timediff = "0.2.3"

enumn = "0.1.13"
crc = "3.0.1"

rodio = { version = "0.17.3", default-features = false }
notify-rust = "4.10.0"

image = "0.24.9"

log = { version = "0.4", features = ["std"] }
env_logger = "0.10.2"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
strip = "debuginfo"
