[package]
name = "roomor"
version = "0.3.11"
edition = "2021"
authors = ["Roman Chumak <p4ymak@yandex.ru>"]
description = "Minimalistic offline chat over local network."
license = "MIT"
repository = "https://github.com/p4ymak/roomor"
readme = "README.md"
categories = ["network-programming"]
keywords = ["chat", "lan", "offline"]
resolver = "2"
build = "build.rs"

[dependencies]
eframe = "0.29.1"
human_bytes = "0.4.3"
opener = "0.7.2"
egui-phosphor = "0.7.3"
flume = "0.11.0"
system-interface = "0.27.2"

whoami = "1.5.2"
directories = "5.0.1"
chrono = "0.4.38"
timediff = "0.2.3"

enumn = "0.1.14"
crc = "3.2.1"
range_rover = "0.1.2"

rodio = { version = "0.19.0", default-features = false }
notify-rust = "4"

log = { version = "0.4", features = ["std"] }
env_logger = "0.11.5"

[target.'cfg(not(target_os = "android"))'.dependencies]
rfd = "0.15"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
strip = "debuginfo"

[package.metadata.bundle]
name = "Roomor"
identifier = "com.p4ymak.roomor"
icon = ["icon/128x128.png"]
version = "0.3.11"
short_description = "Minimalistic offline chat over local network."
long_description = "Minimalistic offline chat with files transmission over local network."
deb_depends = ["libgl1-mesa-glx", "libsdl2-2.0-0 (>= 2.0.5)"]
osx_frameworks = ["SDL2"]

[target.'cfg(windows)'.build-dependencies]
windows_exe_info = "0.4"

[lib]
crate-type=["lib", "cdylib"]

[target.'cfg(target_os = "android")'.dependencies]
eframe = { version = "0.29", default-features = false, features = [ "wgpu", "android-native-activity", "default_fonts" ] }
egui-winit = { version = "0.29", default-features = false, features = [ "clipboard", "links" ] }
android_logger = { version = "0.13", default-features = false }
