[package]
name = "roomor"
version = "0.2.0"
edition = "2021"
authors = ["Roman Chumak <p4ymak@yandex.ru>"]
resolver = "2"
description = "Chat over local network."

[dependencies]
local_ipaddress = "0.1.3"
eframe = "0.26.0"
chrono = "0.4.34"
enumn = "0.1.13"
crc = "3.0.1"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
