[build]
filehash = false
public_url = "/"
dist = "html/"
[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = true
# Disable auto-reload of the web app.
no_autoreload = false
[clean]
# The output dir for all final assets.
dist = "dist"
# Optionally perform a cargo clean.
cargo = false
