use egui_phosphor::regular;

pub const EMOJI_LIST: [&str; 98] = [
    // smiles
    regular::SMILEY,
    regular::SMILEY_WINK,
    regular::SMILEY_MEH,
    regular::SMILEY_SAD,
    regular::SMILEY_ANGRY,
    regular::SMILEY_BLANK,
    regular::SMILEY_NERVOUS,
    regular::SMILEY_X_EYES,
    regular::BABY,
    regular::SMILEY_MELTING,
    // reactions
    regular::THUMBS_UP,
    regular::THUMBS_DOWN,
    regular::ARROW_FAT_UP,
    regular::ARROW_FAT_DOWN,
    regular::CHECK_FAT,
    regular::EYES,
    regular::FIRE,
    regular::HEART,
    regular::CONFETTI,
    regular::STAR,
    regular::SHOOTING_STAR,
    // food
    regular::ACORN,
    regular::AVOCADO,
    regular::BOWL_STEAM,
    regular::CAKE,
    regular::ICE_CREAM,
    regular::COFFEE,
    regular::CARROT,
    regular::CHERRIES,
    regular::HAMBURGER,
    regular::PEPPER,
    regular::PIZZA,
    regular::POPCORN,
    regular::EGG,
    regular::BONE,
    // objects
    regular::SPEAKER_SLASH,
    regular::ALARM,
    regular::WATCH,
    regular::LIGHTBULB,
    regular::PAPERCLIP,
    regular::PENCIL,
    regular::PEN_NIB,
    regular::FEATHER,
    regular::ARCHIVE,
    regular::GIFT,
    regular::CROWN,
    regular::MEDAL,
    regular::TROPHY,
    regular::ARMCHAIR,
    regular::BACKPACK,
    regular::BRIEFCASE,
    regular::BATHTUB,
    regular::TOILET_PAPER,
    regular::BARBELL,
    regular::BEACH_BALL,
    regular::HOCKEY,
    regular::GUITAR,
    regular::PIANO_KEYS,
    regular::PAINT_BRUSH,
    regular::PALETTE,
    regular::HEADPHONES,
    regular::GAME_CONTROLLER,
    regular::UMBRELLA,
    regular::KEY,
    regular::BALLOON,
    regular::TOOTH,
    // weather
    regular::CLOUD,
    regular::CLOUD_SUN,
    regular::CLOUD_MOON,
    regular::CLOUD_FOG,
    regular::CLOUD_LIGHTNING,
    regular::CLOUD_RAIN,
    regular::CLOUD_SNOW,
    regular::MOON,
    // places
    regular::CAR_PROFILE,
    regular::ROCKET,
    regular::STEPS,
    regular::PARK,
    regular::MOUNTAINS,
    regular::ISLAND,
    // animals
    regular::BIRD,
    regular::CAT,
    regular::DOG,
    regular::RABBIT,
    regular::COW,
    regular::BUTTERFLY,
    regular::SHRIMP,
    // plants
    regular::CACTUS,
    regular::FLOWER,
    regular::FLOWER_TULIP,
    regular::FLOWER_LOTUS,
    regular::PLANT,
    regular::CLOVER,
    regular::LEAF,
    regular::GRAINS,
    regular::TREE,
    regular::TREE_EVERGREEN,
    regular::TREE_PALM,
];
